### ISSUE TITLE
DIctionnary Error While TRying on a bunch of samples.

### ISSUE THREAD

**Issue by SpeedyGonzales1234** [DidierStevens/AdHoc#1]
x\xx\Desktop\MAcro-sheetsV\Ab.1234.xls | excel_brute_force_formula_fill.py -e expected.txt
Traceback (most recent call last):
  File "excel_brute_force_formula_fill.py", line 977, in <module>
    Main()
  File "excel_brute_force_formula_fill.py", line 970, in Main
    ProcessTextFiles(oExpandFilenameArguments.Filenames(), oLogfile, options)
  File "excel_brute_force_formula_fill.py", line 918, in ProcessTextFiles
    ProcessTextFile(filename, oBeginGrep, oGrep, oEndGrep, context, oOutput, oLogfile, options)
  File "excel_brute_force_formula_fill.py", line 797, in ProcessTextFile
    for key, row in dCells.items():
RuntimeError: dictionary changed size during iteration

**Comment by SpeedyGonzales1234** [comment]
I can provide the sample upon request

**Comment by SpeedyGonzales1234** [comment]
without quietness :
Traceback (most recent call last):
  File "excel_brute_force_formula_fill.py", line 977, in <module>
    Main()
  File "excel_brute_force_formula_fill.py", line 970, in Main
    ProcessTextFiles(oExpandFilenameArguments.Filenames(), oLogfile, options)
  File "excel_brute_force_formula_fill.py", line 918, in ProcessTextFiles
    ProcessTextFile(filename, oBeginGrep, oGrep, oEndGrep, context, oOutput, oLogfile, options)
  File "excel_brute_force_formula_fill.py", line 788, in ProcessTextFile
    raise Exception('Error row length: ' + repr(row))
Exception: Error row length: ["  2:       288 '\\x05DocumentSummaryInformation'"]
Traceback (most recent call last):
  File "oledump.py", line 2220, in <module>
    sys.exit(Main())
  File "oledump.py", line 2217, in Main
    return OLEDump(args[0], options)
  File "oledump.py", line 2076, in OLEDump
    returnCode, selectionCounter = OLESub(ole, '', rules, options)
  File "oledump.py", line 1831, in OLESub
    print('                 ' + MyRepr(line))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by DidierStevens** [comment]
if the sample is on VT, share the hash here.

remark that these are adhoc tools, that will receive little maintenance.
like you remark for option -q: you have to use option -q, if you don't use it, you'll get an error, as you demonstarted. I will not change this.

**Comment by SpeedyGonzales1234** [comment]
Hi Didier,

First off, thank you for your reply.
The sample in question is not from VT. I'm actually working for or in
conjonction with a world-wide Securite Defense Centre, so, I have a nice
collection of these zloader related maldocs, I can share some of them if
you will.
These are generally quite trivial to manually deobfuscate. But they often
Come with a twist that doesn't allow tools like xlmMacroDeobfuscator to
work with every sample (yet). I thought of starting someting myself, but
since I'm already using your tools, well, it made sense for me to somehow
try to help with your project. I have different on-going projects myself
too, but I might very well be helping with yours at code level too. We'll
see. Anyhow thank you again and have a good day.



Dany Charlier




Le sam. 30 mai 2020 à 11:46, Didier Stevens <notifications@github.com> a
écrit :

**Comment by DidierStevens** [comment]
Hi Dany,

If you can attach the sample here, I'll take a look.

Have a nice day too,

Didier
